# 로컬환경
# spring:
#   security:
#     oauth2: 
#       client:
#         registration:
#           google:
#             client-id: 
#             client-secret: 
#             scope:
#               - email
#               - profile

#           naver:
#             client-id: 
#             client-secret:  
#             scope:
#               - name
#               - email
#             client-name: Naver
#             authorization-grant-type: authorization_code
#             redirect-uri: http://localhost:8081/login/oauth2/code/naver

#         provider:
#           naver:
#             authorization-uri: https://nid.naver.com/oauth2.0/authorize
#             token-uri: https://nid.naver.com/oauth2.0/token
#             user-info-uri: https://openapi.naver.com/v1/nid/me
#             user-name-attribute: response

#   datasource:
#     driver-class-name: org.mariadb.jdbc.Driver
#     url: jdbc:mariadb://localhost:3306/spotify
#     username: hr
#     password: 123456

#   logging:
#     level:
#       org:
#         hibernate:
#           SQL: DEBUG
#           type:
#             descriptor:
#               sql:
#                 BasicBinder: TRACE

#   jpa:
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         show_sql: true
#         format_sql: true

# server:
#   port: 8081

# 도커 환경
 spring:
   security:
     oauth2:
       client: 
         registration:
           google:
             client-id:
             client-secret:
             scope:
               - email
               - profile

           naver:
             client-id:
             client-secret:
             scope:
               - name
               - email
             client-name: Naver
             authorization-grant-type: authorization_code
             redirect-uri: http://localhost:8081/login/oauth2/code/naver

         provider:
           naver:
             authorization-uri: https://nid.naver.com/oauth2.0/authorize
             token-uri: https://nid.naver.com/oauth2.0/token
             user-info-uri: https://openapi.naver.com/v1/nid/me
             user-name-attribute: response

   datasource:
     driver-class-name: org.mariadb.jdbc.Driver
     url: jdbc:mariadb://database-playshare.czo86kyky04z.ap-northeast-2.rds.amazonaws.com:3306/spotify
     username: admin
     password: jaehwan1!

   logging:
     level:
       org:
         hibernate:
           SQL: DEBUG
           type:
             descriptor:
               sql:
                 BasicBinder: TRACE

   jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         show_sql: true
         format_sql: true

 server:
   port: 8081